<?php
/**
 * Created by PhpStorm.
 * User: kartik
 * Date: 2019-09-03
 * Time: 12:58
 */

namespace Personal {

    use SilverStripe\View\Requirements;

    class TimelinePageController extends \PageController {

        public function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
            Requirements::themedJavascript('assets/javascript/timeline');
        }
    }
}